import type { Subject, Student, Teacher, ScheduleEvent, Grade, DashboardStats } from "@/types";

const MockSubjects: Subject[] = [
  { id: 1, code: "CS101", name: "Introduction à la Programmation", departement: "CS", description: "Cours fondamental couvrant les bases de la programmation avec Python, incluant les variables, boucles, fonctions et structures de données.", createdAt: "2025-01-15" },
  { id: 2, code: "MATH201", name: "Analyse Mathématique II", departement: "Math", description: "Étude approfondie des intégrales, séries numériques et équations différentielles avec applications en physique et ingénierie.", createdAt: "2025-02-10" },
  { id: 3, code: "PHY301", name: "Mécanique Quantique", departement: "Physics", description: "Introduction aux principes fondamentaux de la mécanique quantique : dualité onde-particule, équation de Schrödinger et atome d'hydrogène.", createdAt: "2025-03-05" },
  { id: 4, code: "CS201", name: "Structures de Données", departement: "CS", description: "Étude des structures de données avancées : arbres, graphes, tables de hachage et algorithmes de tri et recherche.", createdAt: "2025-01-20" },
  { id: 5, code: "CS301", name: "Bases de Données", departement: "CS", description: "Conception et gestion de bases de données relationnelles, SQL avancé, normalisation et optimisation des requêtes.", createdAt: "2025-02-01" },
  { id: 6, code: "MATH101", name: "Algèbre Linéaire", departement: "Math", description: "Espaces vectoriels, matrices, déterminants, valeurs propres et applications aux systèmes d'équations linéaires.", createdAt: "2025-01-10" },
  { id: 7, code: "PHY201", name: "Électromagnétisme", departement: "Physics", description: "Champs électriques et magnétiques, équations de Maxwell, ondes électromagnétiques et applications.", createdAt: "2025-02-15" },
  { id: 8, code: "CHEM101", name: "Chimie Générale", departement: "Chemistry", description: "Principes fondamentaux de la chimie : structure atomique, liaisons chimiques, thermodynamique et cinétique.", createdAt: "2025-01-25" },
  { id: 9, code: "BIO101", name: "Biologie Cellulaire", departement: "Biology", description: "Structure et fonction des cellules, membranes, organites, division cellulaire et communication intercellulaire.", createdAt: "2025-03-01" },
  { id: 10, code: "CS401", name: "Intelligence Artificielle", departement: "CS", description: "Introduction à l'IA : apprentissage automatique, réseaux de neurones, traitement du langage naturel et vision par ordinateur.", createdAt: "2025-03-10" },
  { id: 11, code: "MATH301", name: "Probabilités et Statistiques", departement: "Math", description: "Théorie des probabilités, variables aléatoires, distributions, tests d'hypothèses et régression.", createdAt: "2025-02-20" },
  { id: 12, code: "CHEM201", name: "Chimie Organique", departement: "Chemistry", description: "Étude des composés organiques, réactions de substitution, élimination, addition et mécanismes réactionnels.", createdAt: "2025-03-15" },
];

const MockStudents: Student[] = [
  { id: 1, matricule: "ETU-2024-001", firstName: "Amadou", lastName: "Diallo", email: "amadou.diallo@univ.mg", dateOfBirth: "2002-03-15", gender: "M", departement: "CS", level: "L3", status: "Actif", enrollmentDate: "2022-09-01", phone: "+261 34 12 345 67", address: "Lot IB 123, Antananarivo" },
  { id: 2, matricule: "ETU-2024-002", firstName: "Fatima", lastName: "Benali", email: "fatima.benali@univ.mg", dateOfBirth: "2003-07-22", gender: "F", departement: "Math", level: "L2", status: "Actif", enrollmentDate: "2023-09-01", phone: "+261 34 23 456 78", address: "Rue de l'Indépendance, Antsirabe" },
  { id: 3, matricule: "ETU-2024-003", firstName: "Jean", lastName: "Rakoto", email: "jean.rakoto@univ.mg", dateOfBirth: "2001-11-08", gender: "M", departement: "Physics", level: "M1", status: "Actif", enrollmentDate: "2021-09-01", phone: "+261 34 34 567 89", address: "Lot IV 456, Fianarantsoa" },
  { id: 4, matricule: "ETU-2024-004", firstName: "Aïcha", lastName: "Traoré", email: "aicha.traore@univ.mg", dateOfBirth: "2002-05-30", gender: "F", departement: "CS", level: "L3", status: "Actif", enrollmentDate: "2022-09-01", phone: "+261 34 45 678 90", address: "Rue du Commerce, Mahajanga" },
  { id: 5, matricule: "ETU-2024-005", firstName: "Pierre", lastName: "Randria", email: "pierre.randria@univ.mg", dateOfBirth: "2000-09-12", gender: "M", departement: "Chemistry", level: "M2", status: "Actif", enrollmentDate: "2020-09-01", phone: "+261 34 56 789 01", address: "Lot III 789, Toamasina" },
  { id: 6, matricule: "ETU-2024-006", firstName: "Marie", lastName: "Rabe", email: "marie.rabe@univ.mg", dateOfBirth: "2003-01-18", gender: "F", departement: "Biology", level: "L1", status: "Actif", enrollmentDate: "2024-09-01", phone: "+261 34 67 890 12", address: "Avenue de France, Antananarivo" },
  { id: 7, matricule: "ETU-2024-007", firstName: "Moussa", lastName: "Koné", email: "moussa.kone@univ.mg", dateOfBirth: "2001-06-25", gender: "M", departement: "CS", level: "M1", status: "Actif", enrollmentDate: "2021-09-01", phone: "+261 34 78 901 23", address: "Lot IVG 321, Antananarivo" },
  { id: 8, matricule: "ETU-2024-008", firstName: "Hanta", lastName: "Razafi", email: "hanta.razafi@univ.mg", dateOfBirth: "2002-12-03", gender: "F", departement: "Math", level: "L3", status: "Actif", enrollmentDate: "2022-09-01", phone: "+261 34 89 012 34", address: "Rue Rainizanabololona, Antsirabe" },
  { id: 9, matricule: "ETU-2024-009", firstName: "Ibrahim", lastName: "Sy", email: "ibrahim.sy@univ.mg", dateOfBirth: "2003-04-07", gender: "M", departement: "Physics", level: "L2", status: "Actif", enrollmentDate: "2023-09-01", phone: "+261 34 90 123 45", address: "Lot II 654, Fianarantsoa" },
  { id: 10, matricule: "ETU-2024-010", firstName: "Noëlla", lastName: "Andriana", email: "noella.andriana@univ.mg", dateOfBirth: "2001-08-19", gender: "F", departement: "CS", level: "L3", status: "Diplômé", enrollmentDate: "2021-09-01", phone: "+261 34 01 234 56", address: "Avenue de l'Indépendance, Antananarivo" },
  { id: 11, matricule: "ETU-2024-011", firstName: "Oumar", lastName: "Bah", email: "oumar.bah@univ.mg", dateOfBirth: "2002-10-14", gender: "M", departement: "Chemistry", level: "L2", status: "Actif", enrollmentDate: "2023-09-01", phone: "+261 34 12 345 00", address: "Lot VB 987, Toamasina" },
  { id: 12, matricule: "ETU-2024-012", firstName: "Soa", lastName: "Ravelona", email: "soa.ravelona@univ.mg", dateOfBirth: "2003-02-28", gender: "F", departement: "Biology", level: "L1", status: "Actif", enrollmentDate: "2024-09-01", phone: "+261 34 23 456 00", address: "Rue Ratsimandrava, Antananarivo" },
  { id: 13, matricule: "ETU-2024-013", firstName: "Bakary", lastName: "Cissé", email: "bakary.cisse@univ.mg", dateOfBirth: "2000-07-11", gender: "M", departement: "Math", level: "M2", status: "Actif", enrollmentDate: "2020-09-01", phone: "+261 34 34 567 00", address: "Avenue Andrianampoinimerina, Antsirabe" },
  { id: 14, matricule: "ETU-2024-014", firstName: "Lalao", lastName: "Raharison", email: "lalao.raharison@univ.mg", dateOfBirth: "2002-09-05", gender: "F", departement: "CS", level: "L2", status: "Suspendu", enrollmentDate: "2023-09-01", phone: "+261 34 45 678 00", address: "Lot IA 147, Mahajanga" },
  { id: 15, matricule: "ETU-2024-015", firstName: "Youssouf", lastName: "Diarra", email: "youssouf.diarra@univ.mg", dateOfBirth: "2001-12-20", gender: "M", departement: "Physics", level: "L3", status: "Actif", enrollmentDate: "2022-09-01", phone: "+261 34 56 789 00", address: "Rue Gallieni, Fianarantsoa" },
  { id: 16, matricule: "ETU-2024-016", firstName: "Voahirana", lastName: "Ratsimba", email: "voahirana.ratsimba@univ.mg", dateOfBirth: "2003-05-16", gender: "F", departement: "Chemistry", level: "L1", status: "Actif", enrollmentDate: "2024-09-01", phone: "+261 34 67 890 00", address: "Avenue de la Libération, Toamasina" },
  { id: 17, matricule: "ETU-2024-017", firstName: "Abdoulaye", lastName: "Ndiaye", email: "abdoulaye.ndiaye@univ.mg", dateOfBirth: "2002-01-09", gender: "M", departement: "Biology", level: "L2", status: "Actif", enrollmentDate: "2023-09-01", phone: "+261 34 78 901 00", address: "Lot IIIG 258, Antananarivo" },
  { id: 18, matricule: "ETU-2024-018", firstName: "Fanja", lastName: "Rasolofo", email: "fanja.rasolofo@univ.mg", dateOfBirth: "2001-03-27", gender: "F", departement: "CS", level: "M1", status: "Actif", enrollmentDate: "2021-09-01", phone: "+261 34 89 012 00", address: "Rue Rabearivelo, Antananarivo" },
  { id: 19, matricule: "ETU-2024-019", firstName: "Sékou", lastName: "Touré", email: "sekou.toure@univ.mg", dateOfBirth: "2003-08-02", gender: "M", departement: "Math", level: "L1", status: "Actif", enrollmentDate: "2024-09-01", phone: "+261 34 90 123 00", address: "Avenue du 26 Juin, Antsirabe" },
  { id: 20, matricule: "ETU-2024-020", firstName: "Hasina", lastName: "Ramana", email: "hasina.ramana@univ.mg", dateOfBirth: "2002-06-13", gender: "F", departement: "Physics", level: "L3", status: "Actif", enrollmentDate: "2022-09-01", phone: "+261 34 01 234 00", address: "Lot VIA 369, Fianarantsoa" },
  { id: 21, matricule: "ETU-2024-021", firstName: "Mamadou", lastName: "Camara", email: "mamadou.camara@univ.mg", dateOfBirth: "2001-11-24", gender: "M", departement: "CS", level: "L3", status: "Inactif", enrollmentDate: "2022-09-01", phone: "+261 34 12 000 00", address: "Rue de la Réunion, Antananarivo" },
  { id: 22, matricule: "ETU-2024-022", firstName: "Mialy", lastName: "Andria", email: "mialy.andria@univ.mg", dateOfBirth: "2003-10-06", gender: "F", departement: "Chemistry", level: "L1", status: "Actif", enrollmentDate: "2024-09-01", phone: "+261 34 23 000 00", address: "Avenue de la Paix, Toamasina" },
  { id: 23, matricule: "ETU-2024-023", firstName: "Issa", lastName: "Keita", email: "issa.keita@univ.mg", dateOfBirth: "2002-04-17", gender: "M", departement: "Biology", level: "L2", status: "Actif", enrollmentDate: "2023-09-01", phone: "+261 34 34 000 00", address: "Lot IB 741, Antananarivo" },
  { id: 24, matricule: "ETU-2024-024", firstName: "Tiana", lastName: "Rakotondra", email: "tiana.rakotondra@univ.mg", dateOfBirth: "2000-08-31", gender: "F", departement: "Math", level: "M2", status: "Actif", enrollmentDate: "2020-09-01", phone: "+261 34 45 000 00", address: "Rue Razafindrahety, Antsirabe" },
  { id: 25, matricule: "ETU-2024-025", firstName: "Cheikh", lastName: "Fall", email: "cheikh.fall@univ.mg", dateOfBirth: "2001-02-14", gender: "M", departement: "CS", level: "M1", status: "Actif", enrollmentDate: "2021-09-01", phone: "+261 34 56 000 00", address: "Avenue Rainilaiarivony, Antananarivo" },
];

const MockTeachers: Teacher[] = [
  { id: 1, matricule: "ENS-001", firstName: "Andry", lastName: "Rajoelina", email: "andry.rajoelina@univ.mg", departement: "CS", specialization: "Intelligence Artificielle", grade: "Professeur", status: "Actif", hireDate: "2010-09-01", phone: "+261 34 11 111 11" },
  { id: 2, matricule: "ENS-002", firstName: "Brice", lastName: "Randrianasolo", email: "brice.randrianasolo@univ.mg", departement: "Math", specialization: "Analyse Numérique", grade: "Maître de Conférences", status: "Actif", hireDate: "2012-09-01", phone: "+261 34 22 222 22" },
  { id: 3, matricule: "ENS-003", firstName: "Claire", lastName: "Razafimahefa", email: "claire.razafimahefa@univ.mg", departement: "Physics", specialization: "Physique Quantique", grade: "Professeur", status: "Actif", hireDate: "2008-09-01", phone: "+261 34 33 333 33" },
  { id: 4, matricule: "ENS-004", firstName: "David", lastName: "Rakotobe", email: "david.rakotobe@univ.mg", departement: "CS", specialization: "Génie Logiciel", grade: "Chargé de Cours", status: "Actif", hireDate: "2015-09-01", phone: "+261 34 44 444 44" },
  { id: 5, matricule: "ENS-005", firstName: "Emma", lastName: "Ratsimba", email: "emma.ratsimba@univ.mg", departement: "Chemistry", specialization: "Chimie Organique", grade: "Maître de Conférences", status: "Actif", hireDate: "2013-09-01", phone: "+261 34 55 555 55" },
  { id: 6, matricule: "ENS-006", firstName: "Fabrice", lastName: "Andriamanalina", email: "fabrice.andriamanalina@univ.mg", departement: "Biology", specialization: "Biologie Moléculaire", grade: "Chargé de Cours", status: "Actif", hireDate: "2016-09-01", phone: "+261 34 66 666 66" },
  { id: 7, matricule: "ENS-007", firstName: "Gisèle", lastName: "Rabemananjara", email: "gisele.rabemananjara@univ.mg", departement: "Math", specialization: "Algèbre", grade: "Professeur", status: "Actif", hireDate: "2005-09-01", phone: "+261 34 77 777 77" },
  { id: 8, matricule: "ENS-008", firstName: "Henri", lastName: "Ravelo", email: "henri.ravelo@univ.mg", departement: "Physics", specialization: "Électromagnétisme", grade: "Assistant", status: "Actif", hireDate: "2019-09-01", phone: "+261 34 88 888 88" },
  { id: 9, matricule: "ENS-009", firstName: "Irène", lastName: "Razafindrabe", email: "irene.razafindrabe@univ.mg", departement: "CS", specialization: "Cybersécurité", grade: "Maître de Conférences", status: "En congé", hireDate: "2011-09-01", phone: "+261 34 99 999 99" },
  { id: 10, matricule: "ENS-010", firstName: "Jacques", lastName: "Ramaroson", email: "jacques.ramaroson@univ.mg", departement: "Chemistry", specialization: "Chimie Analytique", grade: "Assistant", status: "Actif", hireDate: "2020-09-01", phone: "+261 34 10 101 01" },
  { id: 11, matricule: "ENS-011", firstName: "Ketaka", lastName: "Raveloson", email: "ketaka.raveloson@univ.mg", departement: "Biology", specialization: "Écologie", grade: "Maître de Conférences", status: "Actif", hireDate: "2014-09-01", phone: "+261 34 20 202 02" },
  { id: 12, matricule: "ENS-012", firstName: "Luc", lastName: "Andrianaivo", email: "luc.andrianaivo@univ.mg", departement: "CS", specialization: "Réseaux Informatiques", grade: "Chargé de Cours", status: "Actif", hireDate: "2017-09-01", phone: "+261 34 30 303 03" },
];

const MockSchedule: ScheduleEvent[] = [
  { id: 1, subjectId: 1, subjectName: "Introduction à la Programmation", subjectCode: "CS101", teacherId: 1, teacherName: "Pr. Rajoelina", room: "Amphi A", dayOfWeek: "Lundi", startTime: "08:00", endTime: "10:00", level: "L1", departement: "CS", semester: "S1" },
  { id: 2, subjectId: 4, subjectName: "Structures de Données", subjectCode: "CS201", teacherId: 4, teacherName: "M. Rakotobe", room: "Salle 201", dayOfWeek: "Lundi", startTime: "10:00", endTime: "12:00", level: "L2", departement: "CS", semester: "S1" },
  { id: 3, subjectId: 6, subjectName: "Algèbre Linéaire", subjectCode: "MATH101", teacherId: 7, teacherName: "Pr. Rabemananjara", room: "Amphi B", dayOfWeek: "Lundi", startTime: "14:00", endTime: "16:00", level: "L1", departement: "Math", semester: "S1" },
  { id: 4, subjectId: 2, subjectName: "Analyse Mathématique II", subjectCode: "MATH201", teacherId: 2, teacherName: "Dr. Randrianasolo", room: "Salle 102", dayOfWeek: "Mardi", startTime: "08:00", endTime: "10:00", level: "L2", departement: "Math", semester: "S1" },
  { id: 5, subjectId: 7, subjectName: "Électromagnétisme", subjectCode: "PHY201", teacherId: 8, teacherName: "M. Ravelo", room: "Labo Physique", dayOfWeek: "Mardi", startTime: "10:00", endTime: "12:00", level: "L2", departement: "Physics", semester: "S1" },
  { id: 6, subjectId: 5, subjectName: "Bases de Données", subjectCode: "CS301", teacherId: 12, teacherName: "M. Andrianaivo", room: "Salle Info 1", dayOfWeek: "Mardi", startTime: "14:00", endTime: "16:00", level: "L3", departement: "CS", semester: "S1" },
  { id: 7, subjectId: 8, subjectName: "Chimie Générale", subjectCode: "CHEM101", teacherId: 5, teacherName: "Dr. Ratsimba", room: "Labo Chimie", dayOfWeek: "Mercredi", startTime: "08:00", endTime: "10:00", level: "L1", departement: "Chemistry", semester: "S1" },
  { id: 8, subjectId: 9, subjectName: "Biologie Cellulaire", subjectCode: "BIO101", teacherId: 6, teacherName: "M. Andriamanalina", room: "Salle 301", dayOfWeek: "Mercredi", startTime: "10:00", endTime: "12:00", level: "L1", departement: "Biology", semester: "S1" },
  { id: 9, subjectId: 3, subjectName: "Mécanique Quantique", subjectCode: "PHY301", teacherId: 3, teacherName: "Pr. Razafimahefa", room: "Amphi C", dayOfWeek: "Mercredi", startTime: "14:00", endTime: "16:00", level: "L3", departement: "Physics", semester: "S1" },
  { id: 10, subjectId: 10, subjectName: "Intelligence Artificielle", subjectCode: "CS401", teacherId: 1, teacherName: "Pr. Rajoelina", room: "Salle Info 2", dayOfWeek: "Jeudi", startTime: "08:00", endTime: "10:00", level: "M1", departement: "CS", semester: "S1" },
  { id: 11, subjectId: 11, subjectName: "Probabilités et Statistiques", subjectCode: "MATH301", teacherId: 2, teacherName: "Dr. Randrianasolo", room: "Salle 103", dayOfWeek: "Jeudi", startTime: "10:00", endTime: "12:00", level: "L3", departement: "Math", semester: "S1" },
  { id: 12, subjectId: 12, subjectName: "Chimie Organique", subjectCode: "CHEM201", teacherId: 10, teacherName: "M. Ramaroson", room: "Labo Chimie", dayOfWeek: "Jeudi", startTime: "14:00", endTime: "16:00", level: "L2", departement: "Chemistry", semester: "S1" },
  { id: 13, subjectId: 1, subjectName: "Introduction à la Programmation", subjectCode: "CS101", teacherId: 4, teacherName: "M. Rakotobe", room: "Salle Info 1", dayOfWeek: "Vendredi", startTime: "08:00", endTime: "10:00", level: "L1", departement: "CS", semester: "S1" },
  { id: 14, subjectId: 9, subjectName: "Biologie Cellulaire", subjectCode: "BIO101", teacherId: 11, teacherName: "Dr. Raveloson", room: "Labo Bio", dayOfWeek: "Vendredi", startTime: "10:00", endTime: "12:00", level: "L1", departement: "Biology", semester: "S1" },
  { id: 15, subjectId: 6, subjectName: "Algèbre Linéaire", subjectCode: "MATH101", teacherId: 7, teacherName: "Pr. Rabemananjara", room: "Salle 104", dayOfWeek: "Vendredi", startTime: "14:00", endTime: "16:00", level: "L1", departement: "Math", semester: "S1" },
  { id: 16, subjectId: 5, subjectName: "Bases de Données", subjectCode: "CS301", teacherId: 12, teacherName: "M. Andrianaivo", room: "Salle Info 2", dayOfWeek: "Samedi", startTime: "08:00", endTime: "10:00", level: "L3", departement: "CS", semester: "S1" },
  { id: 17, subjectId: 3, subjectName: "Mécanique Quantique", subjectCode: "PHY301", teacherId: 3, teacherName: "Pr. Razafimahefa", room: "Labo Physique", dayOfWeek: "Samedi", startTime: "10:00", endTime: "12:00", level: "L3", departement: "Physics", semester: "S1" },
];

const MockGrades: Grade[] = [
  { id: 1, studentId: 1, studentName: "Amadou Diallo", studentMatricule: "ETU-2024-001", subjectId: 1, subjectName: "Introduction à la Programmation", subjectCode: "CS101", note: 16, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 2, studentId: 1, studentName: "Amadou Diallo", studentMatricule: "ETU-2024-001", subjectId: 4, subjectName: "Structures de Données", subjectCode: "CS201", note: 14, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 3, studentId: 1, studentName: "Amadou Diallo", studentMatricule: "ETU-2024-001", subjectId: 5, subjectName: "Bases de Données", subjectCode: "CS301", note: 15, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 4, studentId: 2, studentName: "Fatima Benali", studentMatricule: "ETU-2024-002", subjectId: 6, subjectName: "Algèbre Linéaire", subjectCode: "MATH101", note: 17, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 5, studentId: 2, studentName: "Fatima Benali", studentMatricule: "ETU-2024-002", subjectId: 2, subjectName: "Analyse Mathématique II", subjectCode: "MATH201", note: 13, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 6, studentId: 3, studentName: "Jean Rakoto", studentMatricule: "ETU-2024-003", subjectId: 3, subjectName: "Mécanique Quantique", subjectCode: "PHY301", note: 12, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 7, studentId: 3, studentName: "Jean Rakoto", studentMatricule: "ETU-2024-003", subjectId: 7, subjectName: "Électromagnétisme", subjectCode: "PHY201", note: 11, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 8, studentId: 4, studentName: "Aïcha Traoré", studentMatricule: "ETU-2024-004", subjectId: 1, subjectName: "Introduction à la Programmation", subjectCode: "CS101", note: 18, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 9, studentId: 4, studentName: "Aïcha Traoré", studentMatricule: "ETU-2024-004", subjectId: 5, subjectName: "Bases de Données", subjectCode: "CS301", note: 15, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 10, studentId: 5, studentName: "Pierre Randria", studentMatricule: "ETU-2024-005", subjectId: 8, subjectName: "Chimie Générale", subjectCode: "CHEM101", note: 14, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 11, studentId: 5, studentName: "Pierre Randria", studentMatricule: "ETU-2024-005", subjectId: 12, subjectName: "Chimie Organique", subjectCode: "CHEM201", note: 16, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 12, studentId: 6, studentName: "Marie Rabe", studentMatricule: "ETU-2024-006", subjectId: 9, subjectName: "Biologie Cellulaire", subjectCode: "BIO101", note: 15, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 13, studentId: 7, studentName: "Moussa Koné", studentMatricule: "ETU-2024-007", subjectId: 10, subjectName: "Intelligence Artificielle", subjectCode: "CS401", note: 17, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 14, studentId: 7, studentName: "Moussa Koné", studentMatricule: "ETU-2024-007", subjectId: 4, subjectName: "Structures de Données", subjectCode: "CS201", note: 13, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 15, studentId: 8, studentName: "Hanta Razafi", studentMatricule: "ETU-2024-008", subjectId: 11, subjectName: "Probabilités et Statistiques", subjectCode: "MATH301", note: 16, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 16, studentId: 8, studentName: "Hanta Razafi", studentMatricule: "ETU-2024-008", subjectId: 6, subjectName: "Algèbre Linéaire", subjectCode: "MATH101", note: 14, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 17, studentId: 9, studentName: "Ibrahim Sy", studentMatricule: "ETU-2024-009", subjectId: 7, subjectName: "Électromagnétisme", subjectCode: "PHY201", note: 9, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 18, studentId: 9, studentName: "Ibrahim Sy", studentMatricule: "ETU-2024-009", subjectId: 3, subjectName: "Mécanique Quantique", subjectCode: "PHY301", note: 8, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 19, studentId: 10, studentName: "Noëlla Andriana", studentMatricule: "ETU-2024-010", subjectId: 1, subjectName: "Introduction à la Programmation", subjectCode: "CS101", note: 19, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 20, studentId: 10, studentName: "Noëlla Andriana", studentMatricule: "ETU-2024-010", subjectId: 10, subjectName: "Intelligence Artificielle", subjectCode: "CS401", note: 17, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 21, studentId: 11, studentName: "Oumar Bah", studentMatricule: "ETU-2024-011", subjectId: 8, subjectName: "Chimie Générale", subjectCode: "CHEM101", note: 10, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 22, studentId: 12, studentName: "Soa Ravelona", studentMatricule: "ETU-2024-012", subjectId: 9, subjectName: "Biologie Cellulaire", subjectCode: "BIO101", note: 13, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 23, studentId: 13, studentName: "Bakary Cissé", studentMatricule: "ETU-2024-013", subjectId: 2, subjectName: "Analyse Mathématique II", subjectCode: "MATH201", note: 18, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 24, studentId: 13, studentName: "Bakary Cissé", studentMatricule: "ETU-2024-013", subjectId: 11, subjectName: "Probabilités et Statistiques", subjectCode: "MATH301", note: 16, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 25, studentId: 14, studentName: "Lalao Raharison", studentMatricule: "ETU-2024-014", subjectId: 1, subjectName: "Introduction à la Programmation", subjectCode: "CS101", note: 7, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 26, studentId: 15, studentName: "Youssouf Diarra", studentMatricule: "ETU-2024-015", subjectId: 3, subjectName: "Mécanique Quantique", subjectCode: "PHY301", note: 14, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 27, studentId: 15, studentName: "Youssouf Diarra", studentMatricule: "ETU-2024-015", subjectId: 7, subjectName: "Électromagnétisme", subjectCode: "PHY201", note: 12, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 28, studentId: 16, studentName: "Voahirana Ratsimba", studentMatricule: "ETU-2024-016", subjectId: 8, subjectName: "Chimie Générale", subjectCode: "CHEM101", note: 15, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 29, studentId: 17, studentName: "Abdoulaye Ndiaye", studentMatricule: "ETU-2024-017", subjectId: 9, subjectName: "Biologie Cellulaire", subjectCode: "BIO101", note: 11, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 30, studentId: 18, studentName: "Fanja Rasolofo", studentMatricule: "ETU-2024-018", subjectId: 10, subjectName: "Intelligence Artificielle", subjectCode: "CS401", note: 16, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 31, studentId: 18, studentName: "Fanja Rasolofo", studentMatricule: "ETU-2024-018", subjectId: 5, subjectName: "Bases de Données", subjectCode: "CS301", note: 14, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 32, studentId: 19, studentName: "Sékou Touré", studentMatricule: "ETU-2024-019", subjectId: 6, subjectName: "Algèbre Linéaire", subjectCode: "MATH101", note: 12, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 33, studentId: 20, studentName: "Hasina Ramana", studentMatricule: "ETU-2024-020", subjectId: 3, subjectName: "Mécanique Quantique", subjectCode: "PHY301", note: 15, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 34, studentId: 20, studentName: "Hasina Ramana", studentMatricule: "ETU-2024-020", subjectId: 7, subjectName: "Électromagnétisme", subjectCode: "PHY201", note: 13, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 35, studentId: 21, studentName: "Mamadou Camara", studentMatricule: "ETU-2024-021", subjectId: 4, subjectName: "Structures de Données", subjectCode: "CS201", note: 6, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 36, studentId: 22, studentName: "Mialy Andria", studentMatricule: "ETU-2024-022", subjectId: 8, subjectName: "Chimie Générale", subjectCode: "CHEM101", note: 14, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 37, studentId: 23, studentName: "Issa Keita", studentMatricule: "ETU-2024-023", subjectId: 9, subjectName: "Biologie Cellulaire", subjectCode: "BIO101", note: 16, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 38, studentId: 24, studentName: "Tiana Rakotondra", studentMatricule: "ETU-2024-024", subjectId: 11, subjectName: "Probabilités et Statistiques", subjectCode: "MATH301", note: 18, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 39, studentId: 24, studentName: "Tiana Rakotondra", studentMatricule: "ETU-2024-024", subjectId: 2, subjectName: "Analyse Mathématique II", subjectCode: "MATH201", note: 17, coefficient: 3, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 40, studentId: 25, studentName: "Cheikh Fall", studentMatricule: "ETU-2024-025", subjectId: 10, subjectName: "Intelligence Artificielle", subjectCode: "CS401", note: 15, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 41, studentId: 25, studentName: "Cheikh Fall", studentMatricule: "ETU-2024-025", subjectId: 4, subjectName: "Structures de Données", subjectCode: "CS201", note: 12, coefficient: 4, semester: "S1", session: "Normale", academicYear: "2025-2026" },
  { id: 42, studentId: 9, studentName: "Ibrahim Sy", studentMatricule: "ETU-2024-009", subjectId: 7, subjectName: "Électromagnétisme", subjectCode: "PHY201", note: 11, coefficient: 3, semester: "S1", session: "Rattrapage", academicYear: "2025-2026" },
  { id: 43, studentId: 9, studentName: "Ibrahim Sy", studentMatricule: "ETU-2024-009", subjectId: 3, subjectName: "Mécanique Quantique", subjectCode: "PHY301", note: 10, coefficient: 4, semester: "S1", session: "Rattrapage", academicYear: "2025-2026" },
  { id: 44, studentId: 14, studentName: "Lalao Raharison", studentMatricule: "ETU-2024-014", subjectId: 1, subjectName: "Introduction à la Programmation", subjectCode: "CS101", note: 10, coefficient: 3, semester: "S1", session: "Rattrapage", academicYear: "2025-2026" },
  { id: 45, studentId: 21, studentName: "Mamadou Camara", studentMatricule: "ETU-2024-021", subjectId: 4, subjectName: "Structures de Données", subjectCode: "CS201", note: 9, coefficient: 4, semester: "S1", session: "Rattrapage", academicYear: "2025-2026" },
];

const MockDashboardStats: DashboardStats = {
  totalStudents: 25,
  totalTeachers: 12,
  totalSubjects: 12,
  averageGrade: 13.8,
  successRate: 82,
  enrollmentTrend: [
    { month: "Sep", count: 180 },
    { month: "Oct", count: 195 },
    { month: "Nov", count: 210 },
    { month: "Dec", count: 205 },
    { month: "Jan", count: 220 },
    { month: "Fev", count: 235 },
    { month: "Mar", count: 248 },
  ],
  gradeDistribution: [
    { range: "0-4", count: 0 },
    { range: "5-7", count: 3 },
    { range: "8-9", count: 4 },
    { range: "10-11", count: 6 },
    { range: "12-13", count: 8 },
    { range: "14-15", count: 10 },
    { range: "16-17", count: 9 },
    { range: "18-20", count: 5 },
  ],
  departmentDistribution: [
    { departement: "CS", students: 9, teachers: 4 },
    { departement: "Math", students: 5, teachers: 2 },
    { departement: "Physics", students: 4, teachers: 2 },
    { departement: "Chemistry", students: 4, teachers: 2 },
    { departement: "Biology", students: 3, teachers: 2 },
  ],
  recentActivity: [
    { id: 1, type: "inscription", description: "Nouvel étudiant inscrit en L1 CS", date: "2026-02-28", actor: "Système" },
    { id: 2, type: "note", description: "Notes du partiel CS301 publiées", date: "2026-02-27", actor: "Pr. Rajoelina" },
    { id: 3, type: "emploi_du_temps", description: "Modification emploi du temps L2 Math", date: "2026-02-26", actor: "Administration" },
    { id: 4, type: "note", description: "Notes du TP PHY201 saisies", date: "2026-02-25", actor: "M. Ravelo" },
    { id: 5, type: "inscription", description: "3 étudiants transférés en M1", date: "2026-02-24", actor: "Scolarité" },
    { id: 6, type: "emploi_du_temps", description: "Ajout cours MATH301 le samedi", date: "2026-02-23", actor: "Administration" },
  ],
};

export { MockSubjects, MockStudents, MockTeachers, MockSchedule, MockGrades, MockDashboardStats };
